
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - monitoring.thedude.cc
  resources:
  - fluentds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.thedude.cc
  resources:
  - fluentds/status
  verbs:
  - get
  - patch
  - update
